### ISSUE TITLE
Allow choosing OpenAI LLM model

### ISSUE THREAD

**Issue by douglasrubims** [douglasrubims/docuforge#4]
Currently, Docuforge uses GPT-4o-mini via OpenAI by default. To provide more flexibility and control over the documentation generation process, we should allow users to choose which OpenAI model to use for their specific needs.

**Proposed Options:**

- **GPT-4 (Standard):** For more complex or nuanced documentation, users can opt for the full GPT-4 model.
- **GPT-4o (Optimized):** A lighter, optimized version of GPT-4, designed for generating high-quality documentation with lower resource usage, suitable for projects requiring balance between performance and cost.
- **GPT-4-turbo:** A faster, cost-effective variant of GPT-4 for users who need quicker responses without sacrificing much quality.
- **GPT-3.5:** For users looking to reduce costs while still generating high-quality documentation, this option offers a more economical solution.
- **Any Future OpenAI Models:** Allow flexibility for users to select any upcoming OpenAI language models, ensuring Docuforge remains adaptable and up-to-date with the latest advancements in AI technology.

**Implementation:**

- Add a flag or configuration option to the CLI that lets users specify which OpenAI model to use.
Example:
  ```bash
  docuforge -p <DIR_PROJECT> --openai-model gpt-3.5
  ```
  Or a `dcf.json` file:
  ```json
  {
    "openaiModel": "gpt-3.5"
  }
  ```

**Comment by AyresMonteiro** [comment]
Added in https://github.com/douglasrubims/docuforge/pull/10
